services:
  app:
    image: ghcr.io/${GITHUB_USER_NAME}/qr-scanner:latest
    command: sh -c "node build/ace.js migration:run --force && node build/bin/server.js"
    env_file:
      - .env
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8000
      - HOST=0.0.0.0
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
